# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VaxMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VaxMe

  # KeychainSwift
  pod 'KeychainSwift', '~> 16.0'
  
  # SnapKit - AutoLayout
  pod 'SnapKit', '~> 5.0.0'

  # Loading Indicators
  pod 'NVActivityIndicatorView', '~> 4.7.0'

  # For caching downloaded images
  pod 'Kingfisher', '~> 5.0'

end
